/* Dynamic Programming — görsel + adım adım mantık */
(function () {
  "use strict";
  const K = window.AZK; if (!K) return;
  const { ri, shuffle, distinct, sum, el, runRounds, tokens, grid, pill } = K;
  const R = {};

  const fib = (n) => { let a = 0, b = 1; for (let i = 0; i < n; i++)[a, b] = [b, a + b]; return a; };
  const climb = (n) => fib(n + 1);
  const rob = (a) => { let inc = 0, exc = 0; for (const x of a) { const ni = exc + x; exc = Math.max(inc, exc); inc = ni; } return Math.max(inc, exc); };
  const coinMin = (co, amt) => { const dp = Array(amt + 1).fill(1e9); dp[0] = 0; for (let i = 1; i <= amt; i++) for (const c of co) if (c <= i) dp[i] = Math.min(dp[i], dp[i - c] + 1); return dp[amt]; };
  const coinWays = (co, amt) => { const dp = Array(amt + 1).fill(0); dp[0] = 1; for (const c of co) for (let i = c; i <= amt; i++) dp[i] += dp[i - c]; return dp[amt]; };
  const lis = (a) => { const d = a.map(() => 1); for (let i = 0; i < a.length; i++) for (let j = 0; j < i; j++) if (a[j] < a[i]) d[i] = Math.max(d[i], d[j] + 1); return Math.max(...d); };
  const knap = (w, v, cap) => { const dp = Array(cap + 1).fill(0); for (let i = 0; i < w.length; i++) for (let c = cap; c >= w[i]; c--) dp[c] = Math.max(dp[c], dp[c - w[i]] + v[i]); return dp[cap]; };
  const upaths = (Rn, Cn) => { const dp = Array(Cn).fill(1); for (let r = 1; r < Rn; r++) for (let c = 1; c < Cn; c++) dp[c] += dp[c - 1]; return dp[Cn - 1]; };
  const minPath = (g) => { const Rn = g.length, Cn = g[0].length, dp = g.map((r) => r.slice()); for (let r = 0; r < Rn; r++) for (let c = 0; c < Cn; c++) { if (!r && !c) continue; dp[r][c] += Math.min(r ? dp[r - 1][c] : 1e9, c ? dp[r][c - 1] : 1e9); } return dp[Rn - 1][Cn - 1]; };
  const edit = (a, b) => { const m = a.length, n = b.length, dp = Array.from({ length: m + 1 }, (_, i) => [i, ...Array(n).fill(0)]); for (let j = 0; j <= n; j++) dp[0][j] = j; for (let i = 1; i <= m; i++) for (let j = 1; j <= n; j++) dp[i][j] = a[i - 1] === b[j - 1] ? dp[i - 1][j - 1] : 1 + Math.min(dp[i - 1][j], dp[i][j - 1], dp[i - 1][j - 1]); return dp[m][n]; };
  const lcs = (a, b) => { const m = a.length, n = b.length, dp = Array.from({ length: m + 1 }, () => Array(n + 1).fill(0)); for (let i = 1; i <= m; i++) for (let j = 1; j <= n; j++) dp[i][j] = a[i - 1] === b[j - 1] ? dp[i - 1][j - 1] + 1 : Math.max(dp[i - 1][j], dp[i][j - 1]); return dp[m][n]; };
  const subset = (a, t) => { const dp = new Set([0]); for (const x of a) for (const sv of [...dp]) dp.add(sv + x); return dp.has(t); };
  const lps = (s) => { const n = s.length, dp = Array.from({ length: n }, () => Array(n).fill(0)); for (let i = n - 1; i >= 0; i--) { dp[i][i] = 1; for (let j = i + 1; j < n; j++) dp[i][j] = s[i] === s[j] ? dp[i + 1][j - 1] + 2 : Math.max(dp[i + 1][j], dp[i][j - 1]); } return dp[0][n - 1]; };
  const rodCut = (p, n) => { const dp = Array(n + 1).fill(0); for (let i = 1; i <= n; i++) for (let j = 1; j <= i; j++) dp[i] = Math.max(dp[i], p[j - 1] + dp[i - j]); return dp[n]; };
  const dice = (d, f, t) => { let dp = Array(t + 1).fill(0); dp[0] = 1; for (let i = 0; i < d; i++) { const nd = Array(t + 1).fill(0); for (let sx = 0; sx <= t; sx++) if (dp[sx]) for (let v = 1; v <= f; v++) if (sx + v <= t) nd[sx + v] += dp[sx]; dp = nd; } return dp[t]; };
  const paintMin = (c) => { let a = c[0][0], b = c[0][1], cc = c[0][2]; for (let i = 1; i < c.length; i++) { const na = c[i][0] + Math.min(b, cc), nb = c[i][1] + Math.min(a, cc), nc = c[i][2] + Math.min(a, b); a = na; b = nb; cc = nc; } return Math.min(a, b, cc); };
  const maxProd = (a) => { let mx = a[0], mn = a[0], best = a[0]; for (let i = 1; i < a.length; i++) { const x = a[i]; if (x < 0)[mx, mn] = [mn, mx]; mx = Math.max(x, mx * x); mn = Math.min(x, mn * x); best = Math.max(best, mx); } return best; };
  const canPart = (a) => { const s = sum(a); return s % 2 === 0 && subset(a, s / 2); };
  const triMin = (t) => { const dp = t[t.length - 1].slice(); for (let r = t.length - 2; r >= 0; r--) for (let c = 0; c <= r; c++) dp[c] = t[r][c] + Math.min(dp[c], dp[c + 1]); return dp[0]; };
  const WORDS = ["KEDI", "ELMA", "OKUL", "BALIK", "GUNES", "DENIZ", "KALEM"];

  function ask(slot, ans, prompt, hint, api, solved) {
    const info = pill(slot, prompt);
    const inp = el("input", "num-input"); inp.type = "number"; inp.placeholder = "?"; slot.appendChild(inp);
    let done = false; const check = () => { if (done || inp.value === "") return; if (+inp.value === ans) { done = true; info.innerHTML = "Doğru ✓"; info.classList.add("hit"); solved(); } else api.penalty(); };
    inp.addEventListener("keydown", (e) => { if (e.key === "Enter") check(); }); api.button("✅ Kontrol Et", "go", check);
    return { hint: () => { inp.value = ans; info.innerHTML = hint; } };
  }
  function askChoice(slot, opts, ans, hint, api, solved) {
    let done = false; const ch = el("div", "choices"); ch.style.maxWidth = "360px";
    opts.forEach((t, idx) => { const c = el("div", "choice", t); c.onclick = () => { if (done) return; if (idx === ans) { done = true; c.classList.add("ok"); solved(); } else { c.classList.add("bad"); api.penalty(); } }; ch.appendChild(c); });
    slot.appendChild(ch); return { hint: () => api.status(hint, "info") };
  }

  R["dp-1"] = (h, api) => { api.prompt("Merdiveni 1 veya 2'şer çıkarak kaç <b>farklı yolla</b> çıkarsın?"); runRounds(h, api, [4, 5, 6], (s, n, d) => ask(s, climb(n), `${n} basamak: kaç yol?`, `İpucu: yol(n)=yol(n-1)+yol(n-2)=${climb(n)} (Fibonacci!).`, api, d)); };
  R["dp-2"] = (h, api) => { api.prompt("Her sayı önceki ikisinin toplamı. <b>Sıradaki</b> Fibonacci?"); runRounds(h, api, [6, 7, 8], (s, n, d) => { const seq = []; for (let i = 1; i <= n; i++) seq.push(fib(i)); tokens(s, seq.concat(["?"]), [n]); return ask(s, fib(n + 1), "Sıradaki sayı?", `İpucu: ${seq[n - 2]}+${seq[n - 1]}=${fib(n + 1)}.`, api, d); }); };
  R["dp-3"] = (h, api) => { api.prompt("Yan yana iki evi soyamazsın. <b>En çok</b> ne kadar?"); runRounds(h, api, [4, 5, 6], (s, n, d) => { const a = Array.from({ length: n }, () => ri(1, 12)); tokens(s, a); return ask(s, rob(a), "En çok ne kadar?", `İpucu: her ev için 'al ya da atla' → ${rob(a)}.`, api, d); }); };
  R["dp-4"] = (h, api) => { api.prompt("Bu paralarla hedefi <b>en az kaç</b> parayla yaparsın?"); runRounds(h, api, [0, 1, 2], (s, l, d) => { const co = [1, 3, 5], amt = ri(7, 15); return ask(s, coinMin(co, amt), `${co.join(", ")}₺ ile ${amt}₺ → en az kaç para?`, `İpucu: dp[t]=1+min dp[t-para]=${coinMin(co, amt)}.`, api, d); }); };
  R["dp-5"] = (h, api) => { api.prompt("Hedefi <b>kaç farklı şekilde</b> yapabilirsin?"); runRounds(h, api, [0, 1, 2], (s, l, d) => { const co = [1, 2, 5], amt = ri(5, 9); return ask(s, coinWays(co, amt), `${co.join(", ")}₺ ile ${amt}₺ → kaç yol?`, `İpucu: ${coinWays(co, amt)} farklı yol.`, api, d); }); };
  R["dp-6"] = (h, api) => { api.prompt("Soldan sağa (atlayarak) <b>artan</b> en uzun dizi kaç sayı?"); runRounds(h, api, [6, 7, 7], (s, n, d) => { const a = shuffle(distinct(n, 1, 20)); tokens(s, a); return ask(s, lis(a), "En uzun artan dizi?", `İpucu: en uzun artan ${lis(a)} sayı.`, api, d); }); };
  R["dp-7"] = (h, api) => { api.prompt("Çanta sınırını aşmadan <b>en değerli</b> yükü seç (0/1 Knapsack)."); runRounds(h, api, [0, 1, 2], (s, l, d) => { const w = [2, 3, 4, 5], v = [3, 4, 5, 6], cap = ri(6, 9); return ask(s, knap(w, v, cap), `Kapasite ${cap} · Ağırlık[${w}] Değer[${v}]`, `İpucu: en yüksek değer ${knap(w, v, cap)}.`, api, d); }); };
  R["dp-8"] = (h, api) => { api.prompt("Sadece SAĞ/AŞAĞI giderek sol üstten sağ alta kaç <b>farklı yol</b>?"); runRounds(h, api, [0, 1, 2], (s, l, d) => { const Rn = ri(2, 4), Cn = ri(2, 4); grid(s, Rn, Cn, { cellClass: () => "water" }); return ask(s, upaths(Rn, Cn), `${Rn}×${Cn} ızgara: kaç yol?`, `İpucu: hücreye yol = üst + sol = ${upaths(Rn, Cn)}.`, api, d); }); };
  R["dp-9"] = (h, api) => { api.prompt("Sağ/aşağı giderek sol üstten sağ alta <b>en küçük</b> toplam?"); runRounds(h, api, [0, 1, 2], (s, l, d) => { const g = Array.from({ length: 3 }, () => Array.from({ length: 3 }, () => ri(1, 9))); grid(s, 3, 3, { cellLabel: (r, c) => g[r][c] }); return ask(s, minPath(g), "En küçük toplam?", `İpucu: her hücre = değeri + min(üst,sol) = ${minPath(g)}.`, api, d); }); };
  R["dp-10"] = (h, api) => { api.prompt("Bir kelimeyi diğerine <b>en az kaç işlemde</b> çevirirsin? (ekle/sil/değiştir)"); runRounds(h, api, [0, 1, 2], (s, l, d) => { const pairs = [["KEDI", "KEDU"], ["EL", "BEL"], ["KAR", "KARA"], ["SU", "SUS"], ["AT", "TAT"]]; const [a, b] = pairs[ri(0, pairs.length - 1)]; return ask(s, edit(a, b), `"${a}" → "${b}": kaç işlem?`, `İpucu: en az ${edit(a, b)} işlem.`, api, d); }); };
  R["dp-11"] = (h, api) => { api.prompt("İki kelimede sırayı bozmadan <b>ortak</b> en uzun harf dizisi kaç harf?"); runRounds(h, api, [0, 1, 2], (s, l, d) => { const a = WORDS[ri(0, WORDS.length - 1)], b = WORDS[ri(0, WORDS.length - 1)]; pill(s, `"${a}" & "${b}"`); return ask(s, lcs(a, b), "Ortak en uzun?", `İpucu: ${lcs(a, b)} harf.`, api, d); }); };
  R["dp-12"] = (h, api) => { api.prompt("Bazılarını seçerek tam hedefe ulaşabilir misin? (Subset Sum)"); runRounds(h, api, [0, 1, 2], (s, l, d) => { const a = distinct(4, 1, 9); const reach = Math.random() < 0.6; let t; if (reach) t = sum(shuffle(a).slice(0, ri(1, 3))); else t = sum(a) + ri(1, 3); const real = subset(a, t); tokens(s, a); return askChoice(s, [`✅ ${t} yapılır`, "❌ İmkânsız"], real ? 0 : 1, real ? "İpucu: bir alt küme hedefe ulaşıyor." : "İpucu: hiçbir alt küme hedefe ulaşmıyor.", api, d); }); };
  R["dp-13"] = (h, api) => { api.prompt("Harf dizisi sözlükteki kelimelere <b>bölünebilir mi</b>? (Word Break)"); runRounds(h, api, [0, 1, 2], (s, l, d) => { const dict = ["EL", "MA", "SU", "KAR", "OT"]; const ok = Math.random() < 0.6; let str = ok ? Array.from({ length: ri(2, 3) }, () => dict[ri(0, dict.length - 1)]).join("") : "ELXMA"; const f = (x) => { if (!x) return true; for (const w of dict) if (x.startsWith(w) && f(x.slice(w.length))) return true; return false; }; const real = f(str); pill(s, `"${str}" · sözlük {${dict.join(", ")}}`); return askChoice(s, ["✅ Bölünür", "❌ Bölünmez"], real ? 0 : 1, real ? "İpucu: baştan sözlük kelimeleriyle ayrılıyor." : "İpucu: bir parça sözlükte yok.", api, d); }); };
  R["dp-14"] = (h, api) => { api.prompt("Harf atlayarak (sıra bozmadan) en uzun <b>palindrom</b> kaç harf?"); runRounds(h, api, [0, 1, 2], (s, l, d) => { const al = "ABC"; let str = ""; for (let i = 0; i < 6; i++) str += al[ri(0, 2)]; tokens(s, str.split("")); return ask(s, lps(str), "En uzun palindrom?", `İpucu: uçlar eşitse +2 → ${lps(str)}.`, api, d); }); };
  R["dp-15"] = (h, api) => { api.prompt("Çubuğu parçalara ayırarak <b>en çok</b> parayı kazan (Rod Cutting)."); runRounds(h, api, [0, 1, 2], (s, l, d) => { const p = [1, 5, 8, 9], n = ri(3, 4); pill(s, `Boy ${n} · 1-4 boy fiyatları [${p}]`); return ask(s, rodCut(p, n), "En çok para?", `İpucu: ilk kesimi dene, kalanı çöz → ${rodCut(p, n)}.`, api, d); }); };
  R["dp-16"] = (h, api) => { api.prompt("2 zar (1-6) atıyorsun. Toplamı hedef yapan <b>kaç sonuç</b> var?"); runRounds(h, api, [0, 1, 2], (s, l, d) => { const t = ri(4, 10); return ask(s, dice(2, 6, t), `Toplam ${t}: kaç farklı sonuç?`, `İpucu: ${dice(2, 6, t)} sonuç.`, api, d); }); };
  R["dp-17"] = (h, api) => { api.prompt("Komşu evler farklı renk olacak. <b>En ucuz</b> boyama? (satır=ev, sütun=🔴🟢🔵)"); runRounds(h, api, [0, 1, 2], (s, l, d) => { const c = Array.from({ length: 3 }, () => [ri(1, 9), ri(1, 9), ri(1, 9)]); grid(s, 3, 3, { cellLabel: (r, cc) => c[r][cc] }); return ask(s, paintMin(c), "En ucuz toplam?", `İpucu: her ev = maliyeti + komşunun farklı renk min = ${paintMin(c)}.`, api, d); }); };
  R["dp-18"] = (h, api) => { api.prompt("Yan yana sayıların <b>en büyük çarpımı</b> (eksiye dikkat!)."); runRounds(h, api, [0, 1, 2], (s, l, d) => { let a; do { a = Array.from({ length: 4 }, () => ri(-3, 4)).filter((x) => x); } while (a.length < 4); a = a.slice(0, 4); tokens(s, a); return ask(s, maxProd(a), "En büyük çarpım?", `İpucu: iki eksi artı yapar → ${maxProd(a)}.`, api, d); }); };
  R["dp-19"] = (h, api) => { api.prompt("Sayıları <b>toplamı eşit</b> iki gruba bölebilir misin?"); runRounds(h, api, [0, 1, 2], (s, l, d) => { const a = distinct(4, 1, 8); const real = canPart(a); tokens(s, a); return askChoice(s, ["✅ Bölünür", "❌ Bölünmez"], real ? 0 : 1, real ? "İpucu: yarısına ulaşılabiliyor." : "İpucu: toplam tek ya da yarısı tutmuyor.", api, d); }); };
  R["dp-20"] = (h, api) => { api.prompt("Sayı üçgeninde tepeden tabana <b>en küçük</b> toplam (her adım alt komşuya)."); runRounds(h, api, [0, 1, 2], (s, l, d) => { const t = [[ri(1, 9)], [ri(1, 9), ri(1, 9)], [ri(1, 9), ri(1, 9), ri(1, 9)]]; s.appendChild(el("div", "visual", t.map((row) => row.map((x) => `<span class='tok'>${x}</span>`).join(" ")).join("<br>"))); return ask(s, triMin(t), "En küçük toplam?", `İpucu: alttan yukarı min topla → ${triMin(t)}.`, api, d); }); };

  K.override(R);
})();
